name: E-grocery News Digest

on:
  schedule:
    - cron: '0 6 1-7 * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
 
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'schedule' && 
       ((github.event.schedule, '%u') == '1') && 
       ((github.event.schedule, '%-d') | int <= 7))
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        CHAT_ID_1: ${{ secrets.CHAT_ID_1 }}
        CHAT_ID_2: ${{ secrets.CHAT_ID_2 }}
      run: python didjest.py
